@extends('layouts.master')
@section('nav')
    @include('partials.nav')
@endsection

@section('title') Terms of Use | FindMeHome @endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Terms of Use</h3>

                <h5>Last Updated: May 10 2017</h5>

                <p>FindMeHome (“FindMeHome”, “we” or “us”) uses this website, https://www.findmehome.xyz (the “Website”), to provide you with information about its products and services and certain information that we or users of the Website have determined to make available on the Website (the “Content”). These Terms of Use refer to Users collectively as "You." Access to and use of the Content on the Website, including any uploading of materials by you to the Website, ordering of services or subscriptions provided through the Website and viewing of the Content on or available through the Website, is subject to your acceptance of and compliance with these terms of use (“Terms of Use”). By using the Website you indicate your acceptance of these Terms of Use. If you do not accept these Terms of Use, then do not use the Website or any of its Content or services.</p>

                <h5>Modifications to this Agreement; Waiver</h5>

                <p>FindMeHome reserves the right to alter, add to, delete, modify or change these Terms of Use at any time. Your use of the Website after any amendments or updates of these Terms of Use shall signify your assent to and acceptance of such revised terms. The most current version of the terms will govern your use of the Website. We will post any changes to the Terms of Use on the Website and update the revision at the beginning of this policy. You should periodically review the Terms of Use to see recent changes. No purported waiver or modification of these Terms of Use by us via telephone or email communications shall be valid or effective.</p>

                <h5>No Implied Advice or Endorsement</h5>
                <p>The Content provided is for `informational purposes only. FindMeHome is not your real estate professional and is not in the business of providing professional real estate advice. If you have any industry related questions, please contact a licensed real estate professional. It is your sole responsibility to determine that a commercial property meets the needs of your business and is suitable for the purposes for which you intend to use it. Similarly, the Website references third parties and third party products and services, but you shall not construe these references as an approval or endorsement by us of that third party, third party product or service.</p>

                <h5>Restrictions on Use of the Website</h5>
                <p>Subject to prior written authorization from FindMeHome, you acknowledge and agree that you may view, download and print the Content, and use the Website and the Content, for your own personal, non-commercial use and in the ordinary course of your business for your internal research and property marketing purposes; and providing information to clients and prospective clients regarding certain commercial properties, provided such information is (i) not sold or generally distributed, (ii)is restricted in scope to a limited number of commercial properties, and (iii) is not a substantial amount of Content, as determined by us in our sole discretion.</p>

                <p>Except as otherwise set out in these Terms of Use or a separate written agreement with FindMeHome, you acknowledge and agree that: (a) you will not, directly or indirectly, sell, assign, distribute, provide access to, transmit, exploit, copy, modify, publish, republish, reproduce, repackage, retransmit, resell, recompile, decompile, disassemble, scrape, extract or otherwise disseminate, the Website or the Content, or any derivative works from the Content, or any portion thereof, in any medium or in any manner whatsoever; and (b) you will not use the Website or the Content to construct a database of any kind, nor store the Website or the Content (in whole or in part) in databases for access by you or any third party, nor distribute any database services containing all or part of the Website or the Content, nor use the Website or the Content in any way to improve the quality of any data sold by you to any third party.</p>

                <p>To inquire about obtaining our written permission to a particular use of the Website or Content, send us an email at contact@findmehome.xyz.</p>

                <p>In addition to complying with these Terms of Use, you shall use the Website, links to other web sites from the Website (the "Linked Sites") for lawful purposes only and you shall use and/or disclose the Content in accordance with all applicable laws, including, without limitation, Canadian privacy laws. You may not: (i) attempt to gain unauthorized access to the Website, or computer systems databases, or networks connected to the Website, through hacking, password or data mining, or any other means to circumvent security procedure; (ii) use the Website in any manner that could damage, disable, overburden, or impair the Website or any service we provide, or interfere with any other party's use and enjoyment of the Website; (iii) use any robot, spider or other automatic device, software program or manual process to monitor, copy or interfere with any web pages or the content contained thereon on the Website; (iv) use any device, software or routine to interfere or attempt to interfere with the proper working of the Website; (v) use the Website to execute denial of service attacks; or (vi) perform automated searches against the Website where, in our reasonable opinion, such searches unduly burden the Website (including, but not limited to automated "bots", crawlers, scrapers or "link checkers").</p>

                <p>Under no circumstances will you use the Website or the Content, or any derivative works from the Content, or any portion thereof, in any manner that may infringe any proprietary or intellectual property rights or interests that FindMeHome and/or any third party may have in the Website or the Content, or any derivative works from the Content, or any portion thereof. You represent and warrant to us that you will not use the Website or Content or any material retrieved from the Content to create products or perform services which compete or interfere with the publications and services of FindMeHome or its licensors.</p>

                <h5>General Rules of User Conduct</h5>
                <p>In using the Website, Content, and any services offered by FindMeHome, you agree not to do any of the following:</p>
                <ul>
                    <li>conduct or promote any illegal activities;</li>
                    <li>interfere with or disrupt the Website or servers or networks connected to the Website;</li>
                    <li>intentionally or unintentionally violate any applicable local, provincial, federal or international law or regulation;</li>
                    <li>attempt to reverse engineer the Website or otherwise attempt to derive the source code of the software (including the tools, methods, processes, and infrastructure) that enables or underlies the Website;</li>
                    <li>attempt to gain access to secured portions of the Website to which you do not possess access rights;</li>
                    <li>use the Website to generate unsolicited email advertisements or spam; or impersonate another user.</li>
                </ul>

                <h5>Accuracy of Information</h5>
                <p>We work hard to make sure all information provided on the Website is accurate, up-to-date and complete. However, the information and materials on the Website may contain errors or inaccuracies, including both typographical and substantive errors. FindMeHome reserves the right, in its sole discretion, without any obligation and without any notice requirement, to discontinue, change, improve or correct the information, materials and descriptions on the Website and to suspend or deny access to the Website for scheduled or unscheduled maintenance, upgrades, improvements or corrections. Any dated information is published as of its date only, and FindMeHome has no responsibility to update or amend any such information.</p>

                <h5>Links to Third-Party Websites</h5>
                <p>The Website contains links to other Linked Sites that are not owned or controlled by us and we are not responsible for the content of any linked websites. The presence on the Website of a link to any other Linked Site does not imply that we endorse or accept any responsibility for the content or use of such website(s), and you hereby release us from all liability and/or damages that may arise from your use of such website(s). While we encourage links to the Website, we reserve the right to prohibit or refuse to accept any link to the Website at any time. You agree to remove any link you may have to the Website upon our request.</p>

                <h5>User-Contributed Content</h5>
                <p>We encourage and need our users to contribute content to the Website. We do not, however, endorse or guarantee the accuracy, completeness, or usefulness of any content posted on the Website by our users. It is your responsibility to evaluate the accuracy, completeness or usefulness of any content posted by other users. You agree not to upload, post or otherwise make available on the Website any material protected by copyright, trademark or other intellectual property or proprietary right without the express permission of the owner of the copyright, trademark or other intellectual property or proprietary right. For instance, when listing space on the Website, you must have right(s) to do so by virtue of being the owner of the material or having the appropriate permissions from the owner. We reserve the right to remove your listing and may terminate your access to the Website if we determine in our discretion that you are not authorized to market a space or upload certain material. You have the burden of determining whether any material can or cannot be submitted or is or is not protected by an intellectual property or proprietary right.</p>

                <p>Subject to a separate written agreement between you and FindMeHome, by submitting material, you grant (or represent and warrant to FindMeHome that the owner of such material has expressly granted) to us the royalty-free, perpetual, irrevocable, non-exclusive right and license to use, sell, reproduce, modify, adapt, publish, perform in public, transmit by way of telecommunication or other means, display, analyse, preserve, translate and distribute such material (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or hereafter developed.</p>

                <p>You also permit any other user of the Website to access, view, store or reproduce the material for that user's personal use and the uses mentioned above under “Restrictions on Use of the Website”. You will indemnify and save FindMeHome, its subsidiaries, affiliates, directors, officers, agents, advisors and employees, harmless for, from and against all claims, losses, costs and expenses resulting from the content and information you supply. You are not entitled to receive any compensation or reimbursement of any kind from us or any of the users of the Website for materials submitted by you. You may not post or otherwise make available on the Website any content that is illegal, obscene, threatening, defamatory, or otherwise injurious to third parties. You may not impersonate any person or entity, or otherwise mislead as to the origin of your content. We have the right, but not the obligation, to monitor the content posted on the Website to determine compliance with our Terms of Use and/or to satisfy any law, regulation or government request. We have the right, in our sole discretion, to edit, refuse to post or remove any material submitted to or posted on the Website. You will upload information that is, to the best of your knowledge, true, complete and accurate.</p>

                <h5>Security</h5>
                <p>Information sent or received over the Internet is generally unsecure and FindMeHome cannot and does not make any representation or warranty concerning security of any communication to or from the Website or any representation or warranty regarding the interception by third parties of personal or other information.</p>

                <h5>Your Subscription</h5>
                <p>If you have registered with us, you are responsible for maintaining the confidentiality of log-in information and for restricting access to your computer, and you agree to accept responsibility and indemnify FindMeHome and its subsidiaries, affiliates, directors, officers, agents, advisors and employees, for all activities that occur under your account or password.</p>

                <p>User privileges are granted by FindMeHome to individuals exclusively and are granted specifically to the subscribing registered user only. User rights cannot be assigned, sublicensed, distributed, shared, viewed, accessed, or otherwise transferred to anyone other than the registered user without the express written permission of FindMeHome. You represent and warrant that the information You provide is true, accurate, complete, and current. Each user must maintain a valid email address and a password to access their FindMeHome account. Users are not permitted to share their individual login information with others. FindMeHome has the right to refuse or terminate service to any user, individual, organization, or firm (and all persons associated or affiliated with said organization or firm) that fails to abide by the Terms of Use.</p>

                <p>Upon registration, which is free, Users becomes a Starter subscriber. A Starter subscription may also list properties on FindMeHome, but lead inquiries with only be accessible within the first 72 hours after being received. By upgrading to a Premium or Unlimited PRO Subscription the User gains unlimited access to their lead inquiries for the duration of the subscription term.</p>

                <h5>Additional Terms</h5>
                <p>Requesting Info and Phone Calls. If you, as a User, choose to contact a real estate professional by filling out a contact or other request form on the Website, you authorize FindMeHome to provide your name and contact information and other identifying information you provide to the applicable real estate professional, and/or other service providers. You acknowledge that, by submitting your contact request or other request form on the Website, you may receive calls from or on behalf of the real estate professional, and/or other service providers, at the telephone number(s) and/or email address you provide.</p>

                <p>The Website may provide phone numbers that can connect you with FindMeHome, its service providers, or other third parties, such as real estate professionals. Some of the numbers listed may be routed through a third party service ("Calling Service"). Calls through the Calling Service may be recorded or monitored for quality assurance and customer service purposes. In the event that you make a call to FindMeHome or through a Calling Service, you consent to such recording and monitoring.FindMeHome will treat recorded calls in accordance with Canadian privacy laws.</p>

                <h5>Disclaimer of all Representations, Warranties and Conditions</h5>
                <p>THE INFORMATION AND MATERIALS PROVIDED ON THE WEBSITE ARE PROVIDED ON AN "AS IS", AS-AVAILABLE BASIS. WE, OUR DIRECTORS, OFFICERS AND EMPLOYEES MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EITHER EXPRESS, IMPLIED, STATUTORY, BY USAGE OF TRADE, COURSE OF DEALING OR OTHERWISE WITH RESPECT TO THE CAPABILITY OF THE WEBSITE OR THE ACCURACY OR THE COMPLETENESS OF THE CONTENT PROVIDED THEREON. ALL WARRANTIES OF ANY TYPE, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WITH RESPECT TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, TITLE, SATISFACTORY QUALITY, PERFORMANCE OR FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY DISCLAIMED. ANY INFORMATION OR MATERIAL ACCESSED, DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE WEBSITE IS AT YOUR OWN DISCRETION AND RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM, LOSS OF DATA, OR ANY OTHER LOSS THAT RESULTS FROM ACCESSING, DOWNLOADING, USING OR RELYING ON ANY SUCH MATERIAL.</p>

                <p>FindMeHome DOES NOT WARRANT, ENDORSE, GUARANTEE, PROVIDE ANY CONDITIONS OR REPRESENTATIONS, OR ASSUME ANY RESPONSIBILITY FOR ANY COMMERCIAL SPACE, PRODUCT OR SERVICE ADVERTISED OR OFFERED BY ANY THIRD PARTY THROUGH THE WEBSITE OR IN RESPECT OF ANY WEBSITE THAT CAN BE REACHED FROM A LINK ON THE WEBSITE, AND FindMeHome SHALL NOT BE A PARTY TO ANY TRANSACTION THAT YOU MAY ENTER INTO WITH ANY SUCH THIRD PARTY.</p>

                <h5>Limitation of Liability and Indemnification</h5>
                <p>YOU EXPRESSLY AGREE THAT YOUR USE OF THIS WEBSITE AND ANY INFORMATION CONTAINED HEREIN IS AT YOUR SOLE RISK. WE ARE NOT LIABLE UNDER CONTRACT LAW, TORT LAW, OR OTHERWISE, FOR ANY DAMAGES OF ANY KIND ARISING FROM YOUR USE OF THIS SITE OR ANY INFORMATION CONTAINED HEREIN. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, IN NO EVENT SHALL FindMeHome BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR OTHER DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS INFORMATION, OR ANY OTHER PECUNIARY LOSS), THESE LIMITATIONS SHALL APPLY EVEN IF FindMeHome HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATIONS SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW. YOU SHALL INDEMNIFY AND HOLD FindMeHome AND ITS SUBSIDIARIES, AFFILIATES, DIRECTORS, OFFICERS AND EMPLOYEES, HARMLESS FROM ALL CLAIMS, THREATS, ACTIONS, PROCEEDINGS, DEMANDS, DAMAGES, LOSSES, OBLIGATIONS, COSTS, AND EXPENSES INCLUDING REASONABLE ATTORNEYS' FEES, MADE BY ANY THIRD PARTY DUE TO OR ARISING OUT OF MATERIALS SUBMITTED, POSTED, TRANSMITTED OR MADE AVAILABLE BY YOU THROUGH THE WEBSITE, YOUR USE OF THE WEBSITE, ANY VIOLATION BY YOU OF THESE TERMS OF USE, OR ANY VIOLATION BY YOU OF ANY RIGHTS OF ANOTHER (INCLUDING, WITHOUT LIMITATION, ALL INTELLECTUAL PROPERTY RIGHTS AND RIGHTS OF PUBLICITY, PERSONALITY OR PRIVACY).</p>

                <p>You expressly acknowledge that FindMeHome is making the Website, Content and links available to you in reliance upon the limitations and exclusions of liability and the disclaimers set forth herein and that the same form an essential basis of the contract between you and FindMeHome. You expressly agree that the limitations and exclusions of liability and the disclaimers set forth herein will survive, and continue to apply in the case of a fundamental breach or breaches of, the failure of essential purpose of contract, the failure of any exclusive remedy or the termination or suspension by FindMeHome of your use of, or access to, the Website.</p>

                <h5>Jurisdiction</h5>
                <p>We do not make any representations and does not give any warranties or conditions that information and materials on the Website are appropriate or available for use outside Canada. Those who choose to access the Website from outside Canada do so on their own initiative and are responsible for compliance with local laws, if and to the extent local laws are applicable. Notwithstanding the foregoing, and recognizing the global nature of the Internet, each viewer and user shall comply with all local rules regarding online conduct and submission of acceptable materials. These Terms of Use are governed and interpreted pursuant to the laws of the Province of British Columbia, Canada, without regard to the conflict of law principles applicable therein, and you agree to submit to the exclusive jurisdiction of the courts located within the Province of British Columbia, Canada. You agree that the provisions of the United Nations Convention on Contracts for the International Sale of Goods shall not apply.</p>

                <h5>Termination</h5>
                <p>We may, under certain circumstances and without prior notice, immediately terminate your ability to access the Website or portions thereof. You acknowledge and agree that all terminations may be made by us in our sole discretion and that we shall not be liable to you or any third-party for any termination of your access to the Website or for the removal of any of the materials uploaded or contributed by you to the Website.</p>

                <h5>Copyright and Trademark Information</h5>

                <p>The Website, and the information and materials that it contains, are the property of FindMeHome, its suppliers, its licensors and other third parties accredited with ownership, and are protected from unauthorized copying and dissemination by copyright law, trademark law, international conventions and other intellectual property laws. All FindMeHome product names and logos are trademarks or registered trademarks of FindMeHome Commercial Listings Ltd. All other company and product names and logos are trademarks or registered trademarks of their respective owners in certain countries. You may neither remove any copyright, trademark or other proprietary notices from any copy nor modify the Content. Nothing contained on the Website should be construed as granting, by implication, estoppel, or otherwise, any license or right to use the Website or any Content, through the use of framing or otherwise, except: (a) as expressly permitted by these Terms of Use; or (b) with the prior written permission of FindMeHome. You shall not attempt to override or circumvent any of the usage rules or restrictions on the Website.</p>

                <p>FindMeHome reserves the right to take such steps as it deems necessary, including without limitation legal action, to restrain unauthorized activity.</p>

            </div>
        </div>
    </div>
    @include('partials.footer')
@endsection